<?php
return [
 'version'=>'yonerge-2026-09-09',
 'matching_default'=>['preference_weight'=>0.75,'transport_weight'=>0.25,'gpa_in_score'=>false,'objectives'=>['yerlesemeyen_sayisi','toplam_puan','yerlesen_normalize_gno','deterministik_esitlik']],
 'EK-8'=>['title'=>'Öğrenci Disiplin, Etik ve İSG Taahhütnamesi','clauses'=>['İşletmenin çalışma düzeni, mesai saatleri, disiplin ve etik kurallarına uyma.','İSG kurallarına uyma, eğitimlere katılma ve kişisel koruyucu donanım kullanma.','Görevleri eğitim amacı ve meslek etiği çerçevesinde yerine getirme.','Eğiticiye ve danışmana bilgi vermeden eğitime ara vermeme veya işletmeyi terk etmeme.','İş yerinde sendikal faaliyetlere katılmama.','Ticari sırları ve gizli bilgileri koruma.','2547 sayılı Kanunun 54. maddesi hükümlerine tabi olma.']],
 'EK-10'=>['title'=>'Gizlilik, Veri Güvenliği ve Fikri Mülkiyet Taahhütnamesi','duration'=>'Eğitim süresince ve bitişinden sonra beş yıl.','clauses'=>['Teknik bilgi, üretim yöntemi, proje, yazılım ve müşteri bilgilerini koruma.','Eğitimde kullanılan not, kayıt ve belgeleri işletmeye teslim etme.','İşletme ile haksız rekabet oluşturan çalışmalardan kaçınma.','Kişisel verileri 6698 sayılı Kanuna uygun işleme ve koruma.','Fikri ürün haklarını ilgili mevzuat ve kayıtlı protokol hükümlerine göre koruma.','Akademik veya teknik yayın için işletmeden yazılı izin alma.']],
 'EK-19'=>['title'=>'Eğitici Personel Taahhüdü','clauses'=>['EK-16 planındaki faaliyetleri yürütme, gerekli iş ve görev dağılımını yapma.','İşe başlamadan İSG eğitimini verme, işe özgü talimatları bildirme ve KKD temin etme.','EK-2 devam çizelgesini düzenli kaydetme.','EK-9 haftalık raporlarını inceleme, onaylama ve yazılı geri bildirim verme.','EK-3 dönem sonu değerlendirmesini rubriklere uygun ve nesnel ölçütlerle yapma.','Öğrenciyi eğitim amacı dışında veya kazanımlarla ilişkisiz işlerde çalıştırmama.','İş kazası, ramak kala ve uygunsuzlukları derhal işletme yetkilisine ve danışmana bildirme.','Yerinde denetim ve çevrim içi izleme görüşmelerine katılma.','Öğrencinin kişisel verilerini 6698 sayılı Kanuna uygun işleme ve gizliliğe uyma.','Nitelik veya görev değişikliğini en geç beş iş günü içinde MYO Müdürlüğüne bildirme.']],
 'rubric_areas'=>['mesleki'=>30,'problem'=>20,'takim'=>15,'etik'=>15,'isg'=>10,'belgeleme'=>10],
 'rubric_levels'=>['yetersiz','gelismekte','yeterli','ustun'],
 'EK-18B_max_scores'=>[20,15,20,10,15,5,5,10],
];
