export const B=JSON.parse(document.getElementById('portal-boot')?.textContent||'null');
export const root=document.getElementById('workspace');
export const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const label=k=>({probability:'Olasılık',severity:'Şiddet',note:'Gerekçe / not',responsible:'Sorumlu',notify:'Bilgilendirilecek makam',permanent_solution:'Kalıcı çözüm / ilgili kayıt',reference:'Dosya / belge referansı',autumn:'Güz yarıyılı',spring:'Bahar yarıyılı',count:'Sayı',participation_percent:'Katılım oranı (%)',completion_percent:'Gerçekleşme oranı (%)',recurring:'Tekrar eden sorun',backup:'Yedek kişi / not',application:'Başvuru',first:'Birinci çalışma',second:'İkinci çalışma'}[k])||B?.ui.fields[k]||B?.ui.labels[k]||({id:'Kayıt',minimum:'Alt sınır',letter:'Harf notu',max_minutes:'Azami dakika',score:'Puan',name:'Adı soyadı',behavior:'Gözlenebilir davranış',value:'Değer',key:'Alan',status:'Durum',student_id:'Öğrenci',offer_id:'İşletme teklifi',eligible:'Uygunluk',proven_optimal:'Optimum ispatlandı',stage:'Aşama',best_bound:'En iyi sınır',gap:'Fark',elapsed_seconds:'Geçen süre',evaluated_students:'Değerlendirilen öğrenci',incomplete_students:'Eksik değerlendirme',average:'Ortalama',above_60_percent:'%60 ve üzerinde başarı oranı',target_met:'Hedef sağlandı',assignment_id:'Görev',actor_id:'İşlemi yapan',target_type:'Kayıt türü',target_id:'İlgili kayıt',occurred_at:'İşlem zamanı',before_hash:'Önceki kayıt özeti',after_hash:'Sonraki kayıt özeti',request_id:'İstek referansı',absent_minutes:'Devamsızlık süresi',expected_minutes:'Beklenen süre',complete:'Kayıtlar tamam',failed:'Devamsızlık sınırı aşıldı',missing_records:'Eksik devam kayıtları',missing_weeks:'Eksik denetim haftaları',workplace_inspections:'İşyeri denetim sayısı',required_workplace_inspections:'Gerekli işyeri denetimi',weekly_requirement_met:'Haftalık denetimler tamam',workplace_requirement_met:'İşyeri denetimleri tamam',missing:'Eksik başlama koşulları',objective_values:'Optimizasyon amaçları',assignments:'Önerilen yerleştirmeler',unplaced:'Yerleşemeyen öğrenciler',dependencies:'Veri sürümleri'}[k])||k.replaceAll('_',' ');
export const value=(v,k='')=>(v==='bekliyor'&&k==='scan_status'?'Tarama bekleniyor':v==='bekliyor'&&k==='result'?'Görüşme bekleniyor':null)||B?.ui.values[v]||B?.ui.labels[v]||({true:'Evet',false:'Hayır',rapor:'Rapor',gorsel:'Görsel',teknik:'Teknik dosya',olcum:'Ölçüm',ekipman:'Ekipman',organizasyon:'Organizasyon',video:'Video',gunluk:'Öğrenme günlüğü',sertifika:'Sertifika',plan:'Plan',oz_degerlendirme:'Öz değerlendirme',devamsizlik:'Devamsızlık',amac_disi:'Eğitim amacı dışı görev',diger:'Diğer',danisma_kurulu:'Danışma Kurulu',isveren:'İşveren',mezun:'Mezun',onlisans:'Ön lisans',ustalik:'Ustalık',mesleki_yeterlilik:'Mesleki yeterlilik',teknik_ogretmenlik:'Teknik öğretmenlik'}[v])||String(v??'—');
export const title=t=>B.ui.labels[t]||({matching:'Akıllı eşleştirme',dashboard:'Genel bakış',reports:'Rapor merkezi',accounts:'Hesap yönetimi',imports:'Öğrenci aktarımı',ek:'EK form merkezi'}[t])||t;
export const badge=s=>`<span class="badge-state ${['onaylandi','ilan_edildi','aktif','basarili','temiz','tamamlandi','danisman_onayi','OPTIMAL'].includes(s)?'good':['basarisiz','zararli','reddedildi','uygun_degil','askida','INFEASIBLE','ERROR'].includes(s)?'bad':['karantina','bekliyor','kuyrukta','iade','eksik','FEASIBLE'].includes(s)?'warn':''}">${esc(value(s))}</span>`;
export function date(v){if(!v)return '—';if(/^\d{4}-\d{2}-\d{2}$/.test(v))return v.split('-').reverse().join('.');const d=new Date(v);return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat('tr-TR',{dateStyle:'medium',timeStyle:'short',timeZone:'Europe/Istanbul'}).format(d);}
export function toast(message,error=false){const n=document.createElement('div');n.className='toast-item'+(error?' error':'');n.setAttribute('role',error?'alert':'status');n.textContent=message;document.getElementById('notice').append(n);setTimeout(()=>n.remove(),7000);}
export async function api(path,{method='GET',data=null,key=null,file=false}={}){
 const headers={Accept:'application/json','X-CSRF-TOKEN':document.querySelector('meta[name="csrf-token"]').content};
 if(method!=='GET')headers['Idempotency-Key']=key||crypto.randomUUID();
 if(data&&!file)headers['Content-Type']='application/json';
 const r=await fetch('/portal-api/v1/'+path,{method,headers,credentials:'same-origin',body:data?(file?data:JSON.stringify(data)):undefined});
 if(r.redirected&&r.url.includes('/giris')){location.href='/giris';throw Error('Oturumunuz sona erdi.');}
 let body;try{body=await r.json();}catch{throw Error('Sunucu yanıtı alınamadı. Oturumunuzu ve bağlantınızı kontrol edin.');}
 if(!r.ok){const e=Error(body.message||'İşlem tamamlanamadı.');e.fields=body.field_errors||body.errors||{};e.status=r.status;e.reference=body.request_id;throw e;}return body;
}
export async function confirmAction(message){const d=document.getElementById('confirm-dialog');document.getElementById('confirm-message').textContent=message;d.returnValue='cancel';d.showModal();return new Promise(resolve=>d.addEventListener('close',()=>resolve(d.returnValue==='confirm'),{once:true}));}
export function empty(message='Henüz kayıt bulunmuyor.',help='Kayıt oluşturulduğunda bu alanda görünecek.'){return `<div class="empty-state"><i class="bi bi-inbox" aria-hidden="true"></i><h2>${esc(message)}</h2><p>${esc(help)}</p></div>`;}
export function pageError(e){const el=document.getElementById('page-error');el.hidden=false;el.className='alert alert-danger';el.textContent=e.message+(e.reference?' İşlem referansı: '+e.reference:'');}
export function recordName(t,r){return r._name||r.legal_name||r.original_name||r.name||r.student_no||r.code||r.number||r.decision_no||r.request_no||(r.week_no?`${r.week_no}. hafta · Sürüm ${r.revision||1}`:'')||(r.month?date(r.month+'-01'):'')||(r.form_code?value(r.form_code):'')||(r.description?String(r.description).slice(0,80):'')||(r.id?`${title(t)} · ${String(r.id).slice(0,8)}`:title(t));}
export async function displayName(t,r){if(r._name||r.name||r.legal_name)return recordName(t,r);if(t==='offers')r._name=(await referenceName('companies',r.company_id))+' · '+(await referenceName('company_sites',r.site_id));if(t==='placements'){try{const s=await api('placements/'+r.id+'/student-summary');r._name=s.name+' · '+s.student_no+' · '+date(r.starts_on);refs.set('students:'+r.student_id,{id:r.student_id,_name:s.name+' · '+s.student_no,student_no:s.student_no});}catch{}}if(t==='applications'&&r.student_id)r._name=(await referenceName('students',r.student_id))+' · '+(await referenceName('academic_terms',r.term_id));return recordName(t,r);}
const refs=new Map();
export async function referenceItems(t,query='',cursor=null){
 let path=t==='users'?'reference-users':t==='applications'&&B.assignment.role==='isletme_yetkilisi'?'interview-candidates':`resources/${t}?limit=100`;
 if(query&&t==='users'&&B.assignment.role==='mudur'&&query.includes('@')){path+='?email='+encodeURIComponent(query);query='';}if(query)path+=(path.includes('?')?'&':'?')+'q='+encodeURIComponent(query);
 if(cursor)path+=(path.includes('?')?'&':'?')+'cursor='+encodeURIComponent(cursor);
 const result=await api(path);for(const r of result.items||[])refs.set(t+':'+r.id,r);if(['offers','placements','applications'].includes(t))for(const r of result.items||[])await displayName(t,r);return result;
}
export function cachedName(t,id){const r=refs.get(t+':'+id);return r?recordName(t,r):null;}
export async function referenceName(t,id){if(!id)return '—';if(refs.has(t+':'+id))return recordName(t,refs.get(t+':'+id));try{const r=await api(`resources/${t}/${id}`);refs.set(t+':'+id,r);return await displayName(t,r);}catch{return 'İlgili kayıt · '+String(id).slice(0,8);}}
export const contextRefs={institution_id:'institutions',program_id:'programs',term_id:'academic_terms',company_id:'companies',student_id:'students',placement_id:'placements'};
export function renderValue(k,v){if(v===null||v===undefined||v==='')return '<span class="muted">Belirtilmedi</span>';if(typeof v==='boolean')return v?'Evet':'Hayır';if(Array.isArray(v)){if(!v.length)return '<span class="muted">Kayıt yok</span>';return '<ul class="mb-0 ps-3">'+v.map(x=>'<li>'+renderValue(k,x)+'</li>').join('')+'</ul>';}if(typeof v==='object')return '<dl class="detail-fields">'+Object.entries(v).filter(([x])=>!['object_key','password','password_confirmation','token'].includes(x)).map(([x,y])=>`<div class="detail-field"><dt>${esc(label(x))}</dt><dd>${renderValue(x,y)}</dd></div>`).join('')+'</dl>';if(/(_on|_at|_until|_from)$/.test(k)&&/^\d{4}-/.test(String(v)))return esc(date(v));return esc(value(v,k));}
export async function download(path,filename){const r=await fetch('/portal-api/v1/'+path,{credentials:'same-origin',headers:{Accept:'application/octet-stream'}});if(!r.ok){let d;try{d=await r.json();}catch{}throw Error(d?.message||'Dosya indirilemedi.');}const url=URL.createObjectURL(await r.blob());const a=document.createElement('a');a.href=url;a.download=filename;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function printHeading(name){return `<div class="print-heading"><h1>Fırat Üniversitesi · ${esc(name)}</h1><p>Mesleki Uygulama Eğitimi · ${esc(B.user.name)} · ${esc(date(new Date().toISOString()))}</p><p>Bu çıktı dijital imza veya resmî karar belgesinin yerine geçmez.</p></div>`;}
export function formError(form,e){let panel=form.querySelector('.form-errors');if(!panel){panel=document.createElement('div');panel.className='form-errors';panel.setAttribute('role','alert');form.prepend(panel);}panel.innerHTML=`<strong>${esc(e.message)}</strong>`+Object.entries(e.fields||{}).map(([k,vs])=>`<div>${esc(label(k.split('.')[0]))}: ${esc((Array.isArray(vs)?vs:[vs]).join(' '))}</div>`).join('');if(e.status===409)panel.innerHTML+='<p class="mb-0 mt-2">Kayıt başka bir işlemle değişmiş olabilir. Güncel ayrıntıyı inceleyip tekrar deneyin; girdiğiniz bilgileri kontrol edin.</p>';panel.scrollIntoView({block:'nearest'});panel.tabIndex=-1;panel.focus();}
