import{sourceFixed,sourceRows}from'./source-fields';
import{B,api,esc,label,value,title,toast,referenceItems,recordName,contextRefs,formError,confirmAction}from'./core';
const q4=['Eğitime devam ve düzen','İşyerine ve ekibe uyum','Haftalık raporların niteliği ve düzenliliği','İSG kurallarına uyum','Görevlerin program çıktılarıyla uyumu','Mesleki gelişim ve öğrenme düzeyi'];
const q11=['Sunum içeriğinin kapsam ve doğruluğu','Uygulama çıktılarının kazanımlarla ilişkisi','Sunum ve ifade becerisi','Eğitim dosyasının niteliği','Soru-cevap ve tartışmaya katkı'];
const performance=['İSG koşulları ve risk kayıtları','Eğitici niteliği ve gözetim yeterliliği','Kazanım ve faaliyet uygunluğu','Değerlendirme ve belgelendirme','Ücret ve mali yükümlülükler','Devam ve bildirim disiplini','Denetim ve iş birliğine katılım','Öğrenci memnuniyeti'];
const portfolio=['İmzalı haftalık raporlar','İzinli fotoğraf ve görseller','Teknik çizim / kod / proje','Ölçüm ve kalite kontrol kayıtları','Ekipman ve yazılım listesi','İSG eğitimi belgesi','İşletme tanıtımı ve organizasyon','Dönem sonu sunum dosyası','Video veya sesli değerlendirme','Öğrenme günlüğü','Sertifika ve eğitim belgeleri','Bireysel öğrenme planı ve revizyonları','Öz değerlendirme çıktıları'];
const hazards=['Elektrik ve topraklama','Makine hareketli elemanları','Yükseklik / kayma / düşme','İşyeri araç trafiği','Kimyasal maruziyet ve depolama','Yangın / patlama / ATEX','Gürültü / titreşim / aydınlatma','Toz / gaz / havalandırma','Elle taşıma ve ergonomi','KKD temini ve kullanımı','Kaynak / kesme / sıcak işler','Basınçlı kap ve hidrolik sistemler','Acil çıkış / tahliye / toplanma','İlk yardım ve acil müdahale','Psikososyal risk ve çalışma süresi','Biyolojik etkenler ve hijyen'];
const reflection=['En çok geliştiğiniz üç alan ve ilgili işler','En zorlandığınız durum ve çözüm yolunuz','Yararlı dersler ve eksik kalan konular','Karşılaştığınız İSG riski ve alınan önlem','Kariyer hedefiniz ve geliştireceğiniz yetkinlikler'];
const competence=['İSG ve risk farkındalığı','Ekip çalışması','Mesleki iletişim','Zaman yönetimi ve devam','Etik ve gizlilik','Problem çözme','Dijital ve teknik araçlar','Öğrenme ve geri bildirim','Kalite ve kaynak verimliliği','Sorumluluk ve inisiyatif'];
const fixed={criteria_scores:null,criterion_scores:performance,reflection_answers:reflection,portfolio_checklist:portfolio,hazard_checklist:hazards,emergency_scenarios:['İş kazası / meslek hastalığı / ramak kala','İşletmenin kapanması / iflası / kontenjan iptali','Deprem / sel / yangın / altyapı kesintisi','Salgın hastalık / karantina / sağlık tedbiri','Öğrenci sağlık / devam / disiplin / uyum durumu','Ücret / katkı / sigorta / ulaşım ve idari aksaklıklar']};
const objectRows={transport_rules:[['max_minutes','Azami tek yön dakika','number'],['score','Ulaşım puanı (0–100)','number']],letter_grade_rules:[['minimum','Alt sınır (0–100)','number'],['letter','Harf notu','text']],levels:[['name','Düzey adı','text'],['behavior','Gözlenebilir davranış','textarea']],criteria:[['code','Ölçüt kodu','text'],['description','Ölçüt açıklaması','textarea']],team:[['name','Adı soyadı','text'],['role','Ekip görevi','text']],participants:[['name','Adı soyadı','text'],['role','Görevi','text']],witnesses:[['name','Tanığın adı soyadı','text'],['contact','İletişim bilgisi','text']],emergency_contacts:[['name','Birim / kişi','text'],['phone','Telefon','text'],['role','Görevi','text']],outcome_attainment:[['program_output_id','Program çıktısı','ref:program_outputs'],['students_above_60_percent','%60 üzeri öğrenci oranı','number']],root_causes:[['problem','Uygunsuzluk / sorun','textarea'],['source','Kaynağı','text'],['impact','Etki düzeyi','text'],['root_cause','Kök neden','textarea']],previous_actions_effects:[['action','Önceki eylem','text'],['status','Gerçekleşme durumu','text'],['evidence','İyileşme kanıtı','text'],['due_on','Yeni termin','date']],outcome_comparison:[['outcome','Öğrenme kazanımı','text'],['previous_evidence','Önceki eğitim kanıtı','textarea'],['comparison','Karşılaştırma','textarea']],statistics:[['indicator','Gösterge','text'],['value','Sayı / oran','number'],['explanation','Açıklama','textarea']],stakeholder_feedback:[['stakeholder','Paydaş','text'],['score','Memnuniyet puanı','number'],['explanation','Görüş','textarea']],inspection_summary:[['activity','İzleme faaliyeti','text'],['planned','Planlanan','number'],['completed','Gerçekleşen','number'],['explanation','Açıklama','textarea']],ohs_statistics:[['indicator','İSG göstergesi','text'],['value','Sayı','number'],['action','Önlem / açıklama','textarea']],evidence_documents:[['document_id','Kanıt belgesi','ref:documents'],['explanation','Açıklama','textarea']],academic_data:[['key','Akademik bilgi / ders','text'],['value','Doğrulanmış değer / durum','text']],course_conditions:[['key','Ders / başvuru koşulu','text'],['value','Durum / beyan','text']],explanations:[['key','Uygunluk ölçütü','text'],['value','İnceleme açıklaması','textarea']],attachments_checklist:[['document','Belge / ek','text'],['available','Mevcut','boolean'],['reference','Referansı','text']],certificates:[['name','Sertifika adı','text'],['issuer','Veren kurum','text'],['date','Tarihi','date']],credited_outcomes:[['outcome_id','Mahsup edilen kazanım','ref:learning_outcomes'],['evidence','Danışman kanıtı / görüşü','textarea']],targets:[['type','İlan türü','enum:placements,success_results'],['id','Onaylı kayıt','target']]};
export const helpers={attendance:'600 saatlik eğitimde mazeretler dahil devamsızlık %20’yi aşarsa değerlendirme yapılmaz. Yalnız gündüz vardiyası kabul edilir.',inspections:'Her hafta en az bir izleme; dönem boyunca en az iki işyeri denetimi gerekir. Çevrim içi denetim için komisyon izni ve EK-13 kaydı zorunludur.',learning_plans:'15 hafta, 600 saat işyeri ve 300 saat bağımsız çalışma. İlk plan on iş günü içinde hazırlanır ve imzalanır. İmzalı belgeler temiz taranmış olmalıdır.',plan_outcomes:'Her kazanım için en az iki bağımsız kanıt kaynağı belirtin.',portfolio_evidence:'Gizli teknik veya görsel materyal için işletmenin yazılı paylaşım izni zorunludur. Tarama bekleyen kanıtlar kullanılamaz.',matching_policies:'Onaylı varsayılan %75 tercih / %25 ulaşım. GNO bu puana eklenmez; üçüncü optimizasyon önceliğidir. Değişiklikler ayrı sürümle onaylanır.',company_performance:'İSG ölçütü 14’ün altında ise yetki askıya alınır. ≥80 üç yıl; 60–79 bir yıl; <60 yetkilendirilemez.',risk_items:'Kalan risk ≥15 ise öğrenci görevlendirilemez. 8–14 aralığında tedbir ve doğrudan gözetim gerekir.',declarations:'Taahhütname metnini okuyun. Kabul kaydı, imzalı belgenin veya kurumsal e-imzanın yerine geçmez.',self_assessments:'Dönem başı değerlendirmesi ilk iki haftada, dönem sonu değerlendirmesi son haftada yapılır. Düzey: 1 henüz yapamıyorum, 2 yakın gözetim, 3 sınırlı rehberlik, 4 bağımsız uygulama.',rubric_evaluations:'Notlar 0–100. Bileşen ağırlıkları: işyeri %40, danışman %30, dosya/portfolyo %20, sunum %10. Alan ağırlıkları ayrıca uygulanır; İSG en az 6/10 gerektirir.',trainer_qualifications:'EK-19 nitelik beyanına öğrenim, deneyim ve belge örneklerini ekleyin. Eğitici başına aynı dönemde en fazla beş öğrenci atanabilir. Nitelik veya görev değişikliği beş iş günü içinde bildirilir.',risk_plans:'Öğrenci odaklı EK-20 planı: her uygulanabilir tehlike için olasılık ve şiddet; altı senaryo için ilk işlemler, sorumlu, bilgilendirilecek makam ve kalıcı çözüm. Görev bazındaki kalan risk ayrıca Risk Maddeleri ekranında değerlendirilir.',feedback:'Ölçek: 1 Kesinlikle katılmıyorum; 2 Katılmıyorum; 3 Kararsızım; 4 Katılıyorum; 5 Kesinlikle katılıyorum.',annual_reports:'EK-18: güz/bahar göstergeleri, kazanım hedefleri, paydaş katılımı, denetim ve İSG, kök neden ve önceki eylemlerin etkisi. Yeni iyileştirme eylemlerini rapora bağlı İyileştirme Eylemleri ekranında tanımlayın.',training_file_deliveries:'Eğitim bitiminden sonraki on iş günü içinde basılı ve elektronik teslim tarihlerini kaydedin.'};
const computed={applications:{eligibility:null,eligibility_reason:null,gpa_snapshot:null,gpa_source:null,gpa_recorded_at:null},attendance:{trainer_approved:false,adviser_reviewed:false},rubric_evaluations:{score:0},payroll:{minimum_due:0,state_contribution:0,employer_share:0},fund_contributions:{total_claim:0},company_performance:{total_score:null,authorization_years:null,authorization_until:null},nonconformities:{authorized_failure:false},change_requests:{credited_minutes:0,credited_outcomes:[]}};
const docRefs={document_id:'documents',decision_document_id:'documents',directorate_document_id:'documents',adaptation_opinion_document_id:'documents'};
fixed.workplace_criteria_scores=['Çalışma saatleri ve işyeri kuralları','İSG tedbirlerine uyma','İletişim ve ekip çalışması','Mesleki sorumluluk ve işin farkındalığı','Teorik bilgiyi uygulamaya aktarma','Araç-gereç ve donanımı uygun kullanma','İşe ilgi, istek ve gayret','Yenilikçilik ve öğrenme isteği','Raporlama ve kayıt tutma','Kendini ifade etme ve geri bildirime açıklık','Fiziki ve zihinsel dayanıklılık','Devam ve genel disiplin'];
objectRows.preferences=[['offer_id','Tercih edilen teklif','ref:offers'],['reachable','Ulaşılabilir','boolean'],['one_way_minutes','Tek yön ulaşım (dakika)','number']];
objectRows.education_records=[['degree','Öğrenim derecesi','text'],['field','Alan / bölüm','text'],['institution','Kurum','text'],['graduation_year','Mezuniyet yılı','number']];
objectRows.experience_records=[['institution','Kurum / işletme','text'],['duty','Görev ve sorumluluk','textarea'],['started_on','Başlangıç','date'],['ended_on','Bitiş','optional:date'],['duration','Süre (yıl-ay)','text']];
Object.assign(objectRows,sourceRows);
let seq=0;
function enumValues(r){const found=r?.match(/(?:^|\|)in:([^|]+)/);return found?found[1].split(','):null;}
function numberAttrs(rule){let s='';const range=rule.match(/(?:between|in):([\d.]+),([\d.]+)(?:\||$)/);if(range&&rule.includes('between:'))s+=` min="${range[1]}" max="${range[2]}"`;const min=rule.match(/min:([\d.]+)/);const max=rule.match(/max:([\d.]+)/);if(min)s+=` min="${min[1]}"`;if(max)s+=` max="${max[1]}"`;return s;}
async function selectReference(select,t,current){let cursor=null;const wrap=select.closest('.ref-control');const search=wrap?.querySelector('[data-ref-search]');const more=wrap?.querySelector('[data-ref-more]');async function load(reset=false){try{const result=await referenceItems(t,search?.value||'',reset?null:cursor);if(reset){select.innerHTML='<option value="">Seçiniz</option>';cursor=null;}for(const r of result.items||[]){if(t==='documents'&&r.scan_status!=='temiz')continue;if(select.querySelector(`option[value="${r.id}"]`))continue;const o=document.createElement('option');o.value=r.id;o.textContent=recordName(t,r)+(r.student_no&&r.name?' · '+r.student_no:'');select.append(o);}cursor=result.next_cursor;if(more)more.hidden=!cursor;if(current&&!Array.from(select.options).some(o=>o.value===String(current))){if(t==='documents'){try{const d=await api('resources/documents/'+current);if(d.scan_status!=='temiz'){current=null;}}catch{current=null;}}if(current){const o=document.createElement('option');o.value=current;o.textContent='Seçili kayıt · '+String(current).slice(0,8);select.append(o);}}if(current)select.value=current;if(select.options.length===2&&!current&&select.required){select.selectedIndex=1;select.dispatchEvent(new Event('change'));}}catch(e){if(wrap){const p=document.createElement('p');p.className='form-text';p.textContent='Bu görev kapsamında seçilebilir kayıt bulunamadı.';wrap.append(p);}}}await load(true);wrap?.querySelector('[data-ref-find]')?.addEventListener('click',()=>load(true));more?.addEventListener('click',()=>load(false));}
function primitive(k,def,v,required=true){const id='f-'+(++seq);const enums=enumValues(def.rules);const req=required&&def.rules?.includes('required')?' required':'';const ref=def.ref||contextRefs[k]||docRefs[k];let input;
 if(ref)input=`<div class="ref-control"><select class="form-select" id="${id}" data-ref="${esc(ref)}" data-current="${esc(v??'')}"${req}><option value="">Yükleniyor…</option></select><div class="d-flex gap-2 mt-1"><input class="form-control form-control-sm" type="search" data-ref-search placeholder="Kayıt ara" aria-label="${esc(label(k))} kayıt araması"><button type="button" class="btn btn-light btn-sm" data-ref-find>Ara</button><button type="button" class="btn btn-light btn-sm" data-ref-more hidden>Daha fazla</button></div>${ref==='documents'?'<p class="form-text">Yalnız taraması tamamlanmış temiz belgeler seçilebilir. Bekleyen belgeyi Belgeler ekranından takip edin.</p>':''}</div>`;
 else if(def.type==='boolean')input=`<select class="form-select" id="${id}"${req}><option value="">Seçiniz</option><option value="true" ${v===true?'selected':''}>Evet</option><option value="false" ${v===false?'selected':''}>Hayır</option></select>`;
 else if(enums)input=`<select id="${id}" class="form-select"${req}><option value="">Seçiniz</option>${enums.map(x=>`<option value="${esc(x)}" ${String(v)===x?'selected':''}>${esc(value(x,k))}</option>`).join('')}</select>`;
 else if(def.type==='text'||def.type==='textarea')input=`<textarea id="${id}" class="form-control" rows="3"${req} maxlength="20000">${esc(v??'')}</textarea>`;
 else{const type=['integer','decimal','number','bigint'].includes(def.type)?'number':def.type==='timestamp'?'datetime-local':def.type==='date'?'date':k==='email'?'email':k==='password'||k==='password_confirmation'?'password':def.type==='file'?'file':'text';let val=v??'';if(type==='datetime-local'&&val){const d=new Date(val);val=new Intl.DateTimeFormat('sv-SE',{timeZone:'Europe/Istanbul',dateStyle:'short',timeStyle:'short'}).format(d).replace(' ','T');}input=`<input id="${id}" class="form-control" type="${type}" value="${type==='file'?'':esc(val)}" ${type==='number'?'step="'+(def.type==='integer'||def.type==='bigint'?'1':'any')+'"'+numberAttrs(def.rules||''):''}${req}${type==='file'?' accept=".pdf,.jpg,.jpeg,.png,.docx"':''}${type==='password'?' autocomplete="new-password" minlength="12"':''}>`;}
 return `<div class="field-control" data-field="${esc(k)}" data-type="${esc(def.type)}"><label class="form-label" for="${id}">${esc(def.label||label(k))}${req?'<span class="text-danger" aria-hidden="true"> *</span>':''}</label>${input}${def.type==='timestamp'?'<div class="form-text">Türkiye saati</div>':''}</div>`;
}
function rowFields(columns,data={}){return columns.map(([k,l,raw])=>{const optional=raw.startsWith('optional:');const t=optional?raw.slice(9):raw;const range=t.split(':');const def={label:l,type:t==='textarea'?'text':t==='number'?'decimal':t.startsWith('integer:')?'integer':t==='boolean'?'boolean':t==='date'?'date':'string',rules:optional?'nullable':'required'};if(t.startsWith('integer:'))def.rules+='|integer|between:'+range[1]+','+range[2];if(t.startsWith('ref:'))def.ref=t.slice(4);if(t.startsWith('enum:'))def.rules+='|in:'+t.slice(5);if(t==='target')def.ref=data.type||'placements';return '<div>'+primitive(k,def,data[k])+'</div>';}).join('');}
function sourceCollection(k,def,v){const spec=sourceFixed[k];const rows=Array.isArray(v)?v:[];return `<div class="field-control wide" data-field="${k}" data-type="source-fixed"><h3 class="h6">${esc(label(k))}</h3><div class="collection">${spec.names.map((name,i)=>{const old=rows[i];const data=old&&typeof old==='object'?old:{value:old??null};return `<section class="collection-row source-row" data-original="${esc(JSON.stringify(data))}"><h4 class="h6">${i+1}. ${esc(name)}</h4>${rowFields(spec.columns,data)}</section>`;}).join('')}</div></div>`;}
function collection(k,def,v,type){if(sourceFixed[k])return sourceCollection(k,def,v);seq++;let names=fixed[k];if(k==='criteria_scores')names=type==='inspections'?q4:q11;if(k==='transferable_competencies')names=competence;if(k==='items')names=B.assignment.role==='ogrenci'?['İşletme, mesleki gelişimime uygun bir eğitim ortamı sağladı.','İşyeri eğitim sorumlusu yeterli rehberlik sağladı.','Akademik danışmanın izleme ve denetimi yeterliydi.','İş sağlığı ve güvenliği önlemleri yeterliydi.','Eğitim kariyer hedeflerime katkı sağladı.']:['Öğrencinin mesleki bilgi ve beceri düzeyi yeterliydi.','Öğrenci çalışma disiplini ve kurallara uyum gösterdi.','Üniversite ile koordinasyon ve iletişim yeterliydi.','Belge ve süreçler açık ve uygulanabilirdi.','İşletmemiz gelecek dönemlerde öğrenci kabul etmeyi düşünmektedir.'];let columns=objectRows[k];if(!columns)columns=[['value',k==='planned_weeks'?'Hafta (1–15)':k==='criterion_values'?'Ölçüt puanı (0–100)':'Bilgi / kanıt kaynağı',k==='planned_weeks'||k==='criterion_values'?'number':'text']];const isMap=['academic_data','course_conditions','explanations'].includes(k);let rows=Array.isArray(v)?v:v&&typeof v==='object'?Object.entries(v).map(([key,x])=>({key,value:x})):[];const size=Number(def.rules?.match(/size:(\d+)/)?.[1]||0);const min=Number(def.rules?.match(/min:(\d+)/)?.[1]||0);
 if(names)return `<div class="field-control wide" data-field="${k}" data-type="fixed" data-fixed-kind="${k==='portfolio_checklist'?'boolean':k==='reflection_answers'||k==='emergency_scenarios'?'text':k==='hazard_checklist'?'hazard':'number'}"><label class="form-label">${esc(label(k))} <span class="text-danger">*</span></label><div class="collection">${names.map((n,i)=>{const val=rows[i]?.value??rows[i]??'';const max=k==='criterion_scores'?[20,15,20,10,15,5,5,10][i]:k==='transferable_competencies'?4:k==='items'?5:100;return `<div class="collection-row"><label for="c-${seq}-${i}">${i+1}. ${esc(n)}</label>${k==='portfolio_checklist'?`<select id="c-${seq}-${i}" class="form-select" data-fixed-value><option value="true" ${val===true?'selected':''}>Var</option><option value="false" ${val===false||val===''?'selected':''}>Yok</option></select>`:k==='reflection_answers'||k==='emergency_scenarios'?`<textarea id="c-${seq}-${i}" class="form-control" data-fixed-value required>${esc(val)}</textarea>`:k==='hazard_checklist'?`<select id="c-${seq}-${i}" class="form-select" data-fixed-value required><option value="">Seçiniz</option>${['Uygun','Önlem gerekli','Uygulanabilir değil'].map(x=>`<option ${val===x?'selected':''}>${x}</option>`).join('')}</select><input class="form-control" aria-label="${esc(n)} gerekçe ve not" data-hazard-note value="${esc(rows[i]?.note||'')}" placeholder="Gerekçe / not">`:`<input id="c-${seq}-${i}" class="form-control" type="number" min="${['transferable_competencies','items'].includes(k)?1:0}" max="${max}" step="any" data-fixed-value required value="${esc(val)}" aria-label="${esc(n)} (azami ${max})">`}</div>`;}).join('')}</div></div>`;
 if(k==='items'){columns=[['value','Geri bildirim ölçütü (1–5)','number']];}
 return `<div class="field-control wide" data-field="${k}" data-type="collection" data-map="${isMap}" data-scalar="${k==='holiday_dates'||!objectRows[k]}" data-columns="${esc(JSON.stringify(columns))}" data-size="${size}" data-min="${min}"><label class="form-label">${esc(label(k))}${def.rules?.includes('required')?' <span class="text-danger">*</span>':''}</label><div class="collection" data-rows>${rows.map((x)=>collectionRow(columns,typeof x==='object'&&x!==null?x:{value:x})).join('')}</div><button class="btn btn-light btn-sm mt-2" type="button" data-add-row><i class="bi bi-plus"></i> Satır ekle</button><p class="form-text">${size?'Tam '+size+' satır gereklidir.':min?'En az '+min+' satır.':'Gerekli bilgileri satır olarak ekleyin.'}</p></div>`;
}
function collectionRow(cols,data={}){return `<div class="collection-row" data-original="${esc(JSON.stringify(data))}">${rowFields(cols,data)}<button type="button" class="btn btn-light btn-sm" data-remove-row aria-label="Satırı kaldır"><i class="bi bi-trash3"></i></button></div>`;}
export async function hydrate(form){for(const s of form.querySelectorAll('[data-ref]'))await selectReference(s,s.dataset.ref,s.dataset.current);for(const c of form.querySelectorAll('[data-type="collection"]')){const cols=JSON.parse(c.dataset.columns);const rows=c.querySelector('[data-rows]');const add=async()=>{rows.insertAdjacentHTML('beforeend',collectionRow(cols));for(const s of rows.lastElementChild.querySelectorAll('[data-ref]'))await selectReference(s,s.dataset.ref,null);};c.querySelector('[data-add-row]').onclick=add;rows.addEventListener('click',e=>{const b=e.target.closest('[data-remove-row]');if(b)b.closest('.collection-row').remove();});if(!rows.children.length){const count=Number(c.dataset.size)||Number(c.dataset.min);for(let i=0;i<count;i++)await add();}}
 // A publication target changes its record selector with the selected result type.
 for(const select of form.querySelectorAll('[data-field="type"] select'))if(select.closest('[data-field="targets"]'))select.addEventListener('change',async()=>{const row=select.closest('.collection-row');const target=row.querySelector('[data-field="id"] select');target.dataset.current='';await selectReference(target,select.value,null);});
}
function readPrimitive(control){const input=control.querySelector('select,input,textarea');if(!input)return null;if(input.type==='file')return input.files[0];if(input.value==='')return null;const t=control.dataset.type;if(t==='boolean')return input.value==='true';if(['integer','bigint','decimal','number'].includes(t))return Number(input.value);if(t==='timestamp')return new Date(input.value+'+03:00').toISOString();return input.value;}
export function readForm(form){const data={};for(const c of form.querySelectorAll('form > .row > [class] > .field-control, [data-top-field]')){const k=c.dataset.field;if(c.dataset.type==='collection'){const rows=Array.from(c.querySelector('[data-rows]').children).map(row=>{const x=JSON.parse(row.dataset.original||'{}');for(const field of row.querySelectorAll('.field-control'))x[field.dataset.field]=readPrimitive(field);return x;});data[k]=c.dataset.map==='true'?Object.fromEntries(rows.filter(x=>x.key).map(x=>[x.key,x.value])):c.dataset.scalar==='true'?rows.map(x=>x.value):rows;}else if(c.dataset.type==='source-fixed'){data[k]=Array.from(c.querySelectorAll('.source-row')).map(row=>{const original=JSON.parse(row.dataset.original||'{}');const x={...original};for(const f of row.querySelectorAll('.field-control'))x[f.dataset.field]=readPrimitive(f);if(k==='hazard_checklist'){if(x.value==='Uygulanabilir değil'&&!x.note?.trim())throw Error('Uygulanabilir olmayan tehlike için gerekçe yazın.');if(x.value!=='Uygulanabilir değil'&&(x.probability===null||x.severity===null))throw Error('Uygulanabilir tehlikelerde olasılık ve şiddet gereklidir.');}return x;});}else if(c.dataset.type==='fixed'){const vals=Array.from(c.querySelectorAll('[data-fixed-value]'));data[k]=vals.map((input,i)=>c.dataset.fixedKind==='boolean'?input.value==='true':c.dataset.fixedKind==='number'?Number(input.value):c.dataset.fixedKind==='hazard'?{value:input.value,note:c.querySelectorAll('[data-hazard-note]')[i].value}:input.value);}else data[k]=readPrimitive(c);}return data;}
export async function openForm({title:heading,fields,initial={},help='',save,confirmation='',defaults={}}){const d=document.getElementById('form-dialog');document.getElementById('form-title').textContent=heading;const mount=document.getElementById('form-content');mount.innerHTML=`${help?`<div class="help-box mb-3">${esc(help)}</div>`:''}<form id="record-form"><div class="row g-3">${Object.entries(fields).map(([k,def])=>`<div class="${def.type==='jsonb'||def.type==='text'||def.type==='textarea'?'col-12':'col-md-6'}">${def.type==='jsonb'?collection(k,def,initial[k]??defaults[k],initial._resource):primitive(k,def,initial[k]??defaults[k])}</div>`).join('')}</div><div class="mt-4 d-flex justify-content-end gap-2"><button type="button" class="btn btn-light" data-close-dialog>Vazgeç</button><button class="btn btn-primary" type="submit" disabled>Kaydet ve devam et</button></div><p class="confirmation-note mt-3 mb-0">Zorunlu alanlar * ile belirtilir. Kayıt ve karar yetkiniz işlem sırasında denetlenir.</p></form>`;const form=mount.querySelector('form');d.showModal();form.onsubmit=e=>e.preventDefault();await hydrate(form);form.querySelector('[type="submit"]').disabled=false;if(['declarations','trainer_qualifications'].includes(initial._resource)){const select=form.querySelector('[data-field="form_code"] select');const panel=document.createElement('div');panel.className='help-box my-3';form.prepend(panel);const show=()=>{const f=B.forms[select?.value||'EK-19'];panel.innerHTML=f?'<strong>'+esc(f.title)+'</strong>'+(f.duration?'<p>'+esc(f.duration)+'</p>':'')+'<ul>'+f.clauses.map(x=>'<li>'+esc(x)+'</li>').join('')+'</ul>':'Taahhütname türünü seçin.';};select?.addEventListener('change',show);show();}let key=crypto.randomUUID();form.addEventListener('input',()=>key=crypto.randomUUID());form.addEventListener('change',()=>key=crypto.randomUUID());form.onsubmit=async e=>{e.preventDefault();if(!form.reportValidity())return;if(confirmation&&!await confirmAction(confirmation))return;const button=form.querySelector('[type="submit"]');button.disabled=true;try{const result=await save({...defaults,...readForm(form)},key);d.close();toast('İşlem başarıyla tamamlandı.');return result;}catch(error){formError(form,error);}finally{button.disabled=false;}};}
export async function resourceForm(type,record=null,after=()=>location.reload(),prefill={}){const spec=B.resources[type];const fields={...spec.fields};const initial={_resource:type,...prefill,...record};for(const [k,v]of Object.entries(computed[type]||{})){delete fields[k];initial[k]=v;}if(type==='weekly_reports'){delete fields.trainer_review;delete fields.adviser_review;}if(type==='role_assignments'){fields.role={type:'string',rules:'required|in:'+B.resources.role_assignments.fields.role.rules.split('in:')[1].split(',').filter(x=>(['sistem_yoneticisi'].includes(B.assignment.role)?x==='sistem_yoneticisi':x!=='sistem_yoneticisi')).join(',')};}if(type==='role_assignments'&&B.assignment.role==='mudur')for(const k of ['program_id','term_id','company_id','student_id'])fields[k]={type:'uuid',rules:'nullable|uuid',ref:contextRefs[k]};if(type==='feedback'&&B.assignment.role!=='isletme_yetkilisi')fields.placement_id={type:'uuid',rules:'required|uuid',ref:'placements'};if(type==='feedback'){fields.source_role={type:'string',rules:'required|in:'+B.assignment.role};initial.source_role=B.assignment.role;}const contexts=spec.required_context.filter(k=>k!=='institution_id'&&!fields[k]);for(const k of contexts)fields[k]={type:'uuid',rules:'required|uuid',ref:contextRefs[k]};const defaults={institution_id:B.assignment.institution_id,...computed[type]};if(B.assignment.program_id)defaults.program_id=B.assignment.program_id;if(B.assignment.term_id)defaults.term_id=B.assignment.term_id;if(B.assignment.company_id)defaults.company_id=B.assignment.company_id;if(B.assignment.student_id)defaults.student_id=B.assignment.student_id;
 if(type==='matching_policies'){defaults.preference_weight=.75;defaults.transport_weight=.25;defaults.revision=1;defaults.seed=crypto.randomUUID();defaults.time_limit_seconds=120;}
 if(type==='declarations'){defaults.text_version=B.forms.version;defaults.accepted_at=new Date().toISOString();}
 if(type==='rubric_evaluations'){defaults.source=B.assignment.role==='egitici'?'is_yeri':'danisman';defaults.revision=record?record.revision:1;}
 if(type==='weekly_reports'||type==='learning_plans')defaults.revision=record?record.revision:1;
 if(type==='programs'||type==='learning_plans'){defaults.workplace_hours=600;defaults.weeks=15;defaults.ects=30;defaults.independent_hours=300;defaults.total_hours=900;defaults.report_portfolio_hours=300;}
 for(const[k,def]of Object.entries(fields)){const single=enumValues(def.rules);if(single?.length===1)defaults[k]=['integer','decimal'].includes(def.type)?Number(single[0]):single[0];}
 if(record){defaults.version=record.version;fields.reason=field('text');}
 if(type==='self_assessments')for(const k of ['portfolio_integrity','evidence_consistency','adviser_feedback'])delete fields[k];
 if(type==='change_requests')delete fields.credit_reviewed_by;
 if(type==='annual_reports')delete fields.board_document_id;
 if(type==='recognition_requests'&&B.assignment.role==='ogrenci')delete fields.board_decision_id;
 
 await openForm({title:(record?'Düzenle · ':'Yeni kayıt · ')+title(type),fields,initial,defaults,help:helpers[type]||'',save:async(data,key)=>{const r=await api('resources/'+type+(record?'/'+record.id:''),{method:record?'PUT':'POST',data,key});after(r);return r;}});
}

export const field=(type='string',required=true,ref=null)=>({type,rules:required?'required':'nullable',ref});
export const decisionFields={decision_no:field(),decision_on:field('date'),document_id:field('uuid',true,'documents'),reason:field('text'),meeting_date:field('date'),members_count:field('integer'),attendees_count:field('integer'),votes_for:field('integer'),votes_against:field('integer'),chair_vote_for:field('boolean'),outcome:{type:'string',rules:'required|in:onay,ret,iade,askiya_alma,fesih'}};
