// Semantic fields from YÖNERGE EK-17–20, stored in the existing JSON collections.
export const portfolioItems=['Haftalık faaliyet raporları (EK-9), tamamı imzalı','Fotoğraf ve görsel kayıtlar (işletme izniyle)','Teknik çizim, şema, devre, kod veya proje','Ölçüm, test, analiz ve kalite kontrol kayıtları','Makine, cihaz, ekipman ve yazılım listesi','İSG katılım belgesi ve talimatları','İşletme tanıtımı ve organizasyon şeması','Dönem sonu sunum dosyası (EK-11)','Video veya sesli değerlendirme (isteğe bağlı)','Öğrenme günlüğü / yansıtıcı düşünme notları','Sertifika, katılım ve eğitim belgeleri','Bireysel öğrenme planı (EK-16) ve revizyonları','EK-17 ve öz değerlendirme çıktıları'];
export const competenceItems=['İSG kurallarına uyma ve risk fark etme','Ekip içinde çalışma ve iş birliği','Sözlü ve yazılı mesleki iletişim','Zaman yönetimi, planlama ve devam disiplini','Mesleki etik, gizlilik ve kurumsal kurallar','Problem tanımlama ve çözüm önerme','Mesleki yazılım, cihaz ve dijital araçlar','Öğrenmeyi öğrenme ve geri bildirimi kullanma','Kalite, çevre ve kaynak verimliliği','Sorumluluk alma ve inisiyatif'];
export const hazardItems=['Elektrik, izolasyon, topraklama ve enerji altında çalışma','Dönen, kesen, ezen makine elemanları ve koruyucular','Yükseklik, düşme, malzeme düşmesi ve kayma','Forklift, transpalet, vinç ve araç trafiği','Kimyasal maruziyet, GBF erişimi ve depolama','Yangın, patlama ve ATEX','Gürültü, titreşim, aydınlatma ve termal konfor','Toz, gaz, buhar ve havalandırma','Elle taşıma ve ergonomi','KKD temini, uygunluğu ve kullanımı','Kaynak, kesme, taşlama ve sıcak işler','Basınçlı kap, kompresör ve hidrolik-pnömatik sistemler','Acil çıkış, tahliye, işaretleme ve toplanma','İlk yardım, revir ve acil müdahale','Psikososyal risk, yıldırma, iş yükü ve çalışma süresi','Biyolojik etkenler ve hijyen'];
export const scenarioItems=['İş kazası, meslek hastalığı şüphesi veya ramak kala','İşletmenin kapanması, iflası veya kontenjan iptali','Deprem, sel, yangın, afet ve altyapı kesintisi','Salgın hastalık, karantina veya toplu sağlık tedbiri','Öğrencinin sağlık, devam, disiplin veya uyum sorunu','Ücret, devlet katkısı, sigorta, ulaşım ve konaklama aksaklıkları'];
export const sourceFixed={
 portfolio_checklist:{names:portfolioItems,columns:[['value','Durum','boolean'],['reference','Dosya adı / belge referansı','optional:text'],['date','Tarih','optional:date']]},
 transferable_competencies:{names:competenceItems,columns:[['value','Bu ölçümde düzey (1–4)','integer:1:4'],['explanation','Kısa açıklama','optional:textarea']]},
 hazard_checklist:{names:hazardItems,columns:[['value','Kontrol durumu','enum:Uygun,Önlem gerekli,Uygulanabilir değil'],['probability','Olasılık (1–5)','optional:integer:1:5'],['severity','Şiddet (1–5)','optional:integer:1:5'],['note','Uygulanabilir değilse gerekçe / not','optional:textarea']]},
 emergency_scenarios:{names:scenarioItems,columns:[['value','Derhal uygulanacak işlemler (0–24 saat)','textarea'],['responsible','Sorumlu','text'],['notify','Bilgilendirilecek makam','text'],['permanent_solution','Kalıcı çözüm / ilgili kayıt','textarea']]},
};
export const sourceRows={
 holiday_dates:[['value','Resmî tatil tarihi','date']],
 certificates:[['name','Belge / yeterlilik adı','text'],['issuer','Veren kurum','text'],['number','Belge numarası','optional:text'],['date','Tarihi','date'],['document_id','Belge eki','optional:ref:documents']],
 emergency_contacts:[['role','Görev / unvan','text'],['name','Adı soyadı','text'],['phone','Telefon','text'],['backup','Yedek kişi / not','optional:text']],
 statistics:[['indicator','Gösterge','text'],['autumn','Güz yarıyılı','optional:number'],['spring','Bahar yarıyılı','optional:number'],['value','Toplam sayı / oran','optional:number'],['explanation','Açıklama','optional:textarea']],
 outcome_attainment:[['program_output_id','Program çıktısı','ref:program_outputs'],['outcome','Öğrenme kazanımı / ifade','optional:textarea'],['rubric','Ölçme aracı / rubrik','optional:text'],['target_percent','Hedef eşik (%)','optional:integer:0:100'],['average','Gerçekleşen ortalama','optional:number'],['students_above_60_percent','60/100 eşiğini aşan öğrenci oranı (%)','integer:0:100'],['target_met','Hedefe ulaşıldı mı?','optional:boolean']],
 stakeholder_feedback:[['stakeholder','Paydaş grubu','text'],['count','Anket / görüşme sayısı','optional:integer:0:100000'],['participation_percent','Katılım oranı (%)','optional:integer:0:100'],['score','Memnuniyet ortalaması (1–5)','number'],['explanation','Öne çıkan ilk üç bulgu','textarea']],
 inspection_summary:[['activity','İzleme faaliyeti','text'],['planned','Planlanan','number'],['completed','Gerçekleşen','number'],['completion_percent','Gerçekleşme oranı (%)','optional:number'],['explanation','Açıklama','textarea']],
 root_causes:[['problem','Uygunsuzluk / sorun','textarea'],['source','Kaynağı','text'],['impact','Etki düzeyi','enum:Düşük,Orta,Yüksek'],['root_cause','Kök neden','textarea'],['recurring','Tekrar eden sorun mu?','optional:boolean']],
};
