<!doctype html><html lang="tr"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>MUE Backend İşletim Konsolu</title>
<style>body{max-width:1000px;margin:3rem auto;font:16px system-ui;background:#f3f5f8;color:#17243b}section{background:white;padding:1.5rem;margin:1rem 0;border-radius:12px}input,select,textarea,button{font:inherit;padding:.65rem;margin:.25rem}textarea{width:95%;min-height:180px}pre{white-space:pre-wrap;overflow-wrap:anywhere}button{background:#164980;color:white;border:0;border-radius:6px}label{display:block}</style>
<h1>3+1 Mesleki Uygulama Eğitimi</h1><p>Backend işletim konsolu. Üretim portalı Prompt 2 kapsamında hazırlanacaktır.</p>
<section><h2>Giriş ve görev seçimi</h2><label>E-posta <input id="email" type="email" autocomplete="username"></label><label>Parola <input id="password" type="password" autocomplete="current-password"></label><button id="login">Giriş yap</button><label>Aktif görev <select id="assignment"></select></label><button id="logout">Çıkış</button></section>
<section><h2>API isteği</h2><label>Yöntem <select id="method"><option>GET</option><option>POST</option><option>PUT</option></select></label><label>API yolu <input id="path" size="65" value="/api/v1/schema"></label><label>JSON içerik <textarea id="body">{}</textarea></label><button id="send">İsteği çalıştır</button><button id="schema">Alan sözleşmesini getir</button><pre id="result" role="status"></pre></section>
<script>let token='',key=crypto.randomUUID();const el=id=>document.getElementById(id);function show(v){el('result').textContent=JSON.stringify(v,null,2)}
el('login').onclick=async()=>{try{let r=await fetch('/api/v1/auth/login',{method:'POST',headers:{'Content-Type':'application/json','Accept':'application/json'},body:JSON.stringify({email:el('email').value,password:el('password').value})});let d=await r.json();if(!r.ok){show(d);return}token=d.token;el('password').value='';el('assignment').replaceChildren(...d.assignments.map(a=>{let o=document.createElement('option');o.value=a.id;o.textContent=a.role+' • '+(a.program_id||'MYO');return o}));show({message:d.message,user:d.user});}catch(e){show({message:'Bağlantı kurulamadı.'})}};
el('send').onclick=async()=>{try{let path=el('path').value;if(!path.startsWith('/api/v1/'))throw Error();let method=el('method').value;let headers={'Accept':'application/json','Content-Type':'application/json','Authorization':'Bearer '+token,'X-Assignment-Id':el('assignment').value,'Idempotency-Key':key};let r=await fetch(path,{method,headers,...(method==='GET'?{}:{body:JSON.stringify(JSON.parse(el('body').value))})});show({http:r.status,response:await r.json()});}catch(e){show({message:'JSON içerik veya API yolu geçersiz; bağlantıyı kontrol edin.'})}};
['body','path','method'].forEach(id=>el(id).addEventListener('input',()=>key=crypto.randomUUID()));el('schema').onclick=()=>{el('path').value='/api/v1/schema';el('method').value='GET';el('send').click()};el('logout').onclick=async()=>{if(token)await fetch('/api/v1/auth/logout',{method:'POST',headers:{Authorization:'Bearer '+token,Accept:'application/json'}});token='';el('assignment').replaceChildren();show({message:'Oturum kapatıldı.'})};</script></html>
