@extends('portal.layout')
@section('title',$mode==='login'?'Giriş':($mode==='forgot'?'Parolamı unuttum':'Parola yenileme'))
@section('body-class','auth-page')
@section('content')
<div class="auth-top"><img src="{{ asset('images/firat-logo.png') }}" alt="Fırat Üniversitesi" width="54" height="54"><span>FIRAT ÜNİVERSİTESİ<br><small>Elazığ Organize Sanayi Bölgesi MYO</small></span></div>
<main id="main" class="auth-shell"><section class="auth-intro"><span class="eyebrow">MESLEKİ UYGULAMA EĞİTİMİ</span><h1>Bilgiden deneyime.<br>Birlikte, bir adım ileri.</h1><p>3+1 eğitim yolculuğunuzu tek bir yerde yönetin. Başvuru, yerleştirme, eğitim ve değerlendirme süreçlerine görevinizle erişin.</p><div class="journey-grid"><div><b>01</b><span>Başvuru ve tercih</span></div><div><b>02</b><span>İşyeri deneyimi</span></div><div><b>03</b><span>Kazanım ve gelişim</span></div></div><div class="institution-note"><i class="bi bi-mortarboard" aria-hidden="true"></i><span>15 hafta · 600 saat işyeri eğitimi<br><strong>Öğrenci, üniversite ve işletme aynı süreçte.</strong></span></div></section>
<section class="auth-card"><div class="auth-card-heading"><span class="small-mark">MÜE</span><span class="eyebrow">3+1 YÖNETİM SİSTEMİ</span></div><h2>{{ $mode==='login'?'Hesabınıza giriş yapın':($mode==='forgot'?'Parolanızı yenileyin':'Yeni parolanızı belirleyin') }}</h2><p class="muted">{{ $mode==='login'?'Kurumsal hesabınız ve size tanımlanan görevlerle devam edin.':'Parola işlemleri kurumsal e-posta servisini kullanır.' }}</p>
@if(session('success'))<div class="alert alert-success" role="status">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger" role="alert">@foreach($errors->all() as $error)<p class="mb-1">{{ $error }}</p>@endforeach</div>@endif
<form action="{{ $mode==='login'?'/giris':($mode==='forgot'?'/parolami-unuttum':'/parola-yenile') }}" method="post">@csrf
@if($mode==='reset')<input type="hidden" name="token" value="{{ $token }}">@endif
<div class="mb-3"><label class="form-label" for="email">E-posta adresi</label><input class="form-control" id="email" type="email" name="email" required autocomplete="username" value="{{ old('email',$email??'') }}" placeholder="ad.soyad@kurum.edu.tr"></div>
@if($mode!=='forgot')<div class="mb-3"><label class="form-label" for="password">Parola</label><div class="input-group"><input class="form-control" id="password" type="password" name="password" required autocomplete="{{ $mode==='login'?'current-password':'new-password' }}" @if($mode==='reset') minlength="12" @endif><button type="button" class="btn btn-outline-secondary" data-toggle-password="password" aria-label="Parolayı göster"><i class="bi bi-eye" aria-hidden="true"></i></button></div></div>@endif
@if($mode==='reset')<div class="mb-3"><label for="password_confirmation" class="form-label">Yeni parola tekrarı</label><input id="password_confirmation" class="form-control" name="password_confirmation" type="password" autocomplete="new-password" required minlength="12"><p class="form-text">En az 12 karakter; büyük/küçük harf, sayı ve simge.</p></div>@endif
@if($mode==='login')<div class="mb-3"><label class="form-label" for="otp">Doğrulayıcı uygulama kodu</label><input class="form-control" id="otp" name="otp" inputmode="numeric" autocomplete="one-time-code" pattern="[0-9]{6}" maxlength="6" aria-describedby="otp-help"><p id="otp-help" class="form-text">Çok faktörlü giriş tanımlandıysa güncel altı haneli kodu girin. Yetkili hesaplarda kurulum kurumun hesap sorumlusu tarafından tamamlanır.</p></div>@endif
<button type="submit" class="btn btn-primary w-100 py-3">{{ $mode==='login'?'Giriş yap':($mode==='forgot'?'Yenileme bağlantısı iste':'Parolayı yenile') }} <i class="bi bi-arrow-right ms-2" aria-hidden="true"></i></button></form>
<div class="d-flex justify-content-between mt-3 small"><a href="{{ $mode==='login'?'/parolami-unuttum':'/giris' }}">{{ $mode==='login'?'Parolamı unuttum':'Giriş sayfasına dön' }}</a><span class="muted">Güvenli kurumsal erişim</span></div>
@if($mode==='login')<div class="portal-identities"><span>Öğrenci</span><span>Akademik danışman</span><span>İşletme</span><span>MYO yetkilisi</span></div><p class="small muted mt-3 mb-0">Giriş yapmak yeni bir görev veya akademik yetki vermez.</p>@endif
</section></main><footer class="auth-footer">Fırat Üniversitesi · Mesleki Uygulama Eğitimi Yönetim Sistemi</footer>
@endsection
