@extends('portal.layout')
@php
$role=$assignment->role;
$portal=match($role){'ogrenci'=>'Öğrenci Portalı','akademik_danisman'=>'Akademik Danışman Portalı','egitici','isletme_yetkilisi'=>'İşletme Portalı',default=>'MYO Yönetim Portalı'};
$titles=['dashboard'=>'Genel bakış','matching'=>'Akıllı eşleştirme','reports'=>'Rapor merkezi','accounts'=>'Hesap yönetimi','imports'=>'Öğrenci aktarımı','ek'=>'EK form merkezi'];
$title=$titles[$page]??config('portal.labels.'.$page,'Mesleki Uygulama Eğitimi');
$priority=match($role){'ogrenci'=>['applications','preferences','offers','placements','weekly_reports','portfolio_evidence','success_results'],'akademik_danisman'=>['students','placements','learning_plans','inspections','weekly_reports','rubric_evaluations'],'isletme_yetkilisi'=>['companies','company_sites','trainer_qualifications','offers','capacity_requests','interviews','placements'],'egitici'=>['placements','learning_plans','attendance','weekly_reports','rubric_evaluations'],default=>['applications','companies','placements','academic_terms','decisions','publications']};
@endphp
@section('title',$title)
@section('content')
<div class="portal-shell"><aside class="sidebar" id="sidebar" aria-label="Ana gezinme"><button type="button" class="icon-button menu-toggle sidebar-close" id="menu-close" aria-label="Menüyü kapat"><i class="bi bi-x-lg"></i></button><a class="brand" href="/panel"><img src="{{ asset('images/firat-logo.png') }}" width="48" height="48" alt="Fırat Üniversitesi"><span>FIRAT ÜNİVERSİTESİ<small>MESLEKİ UYGULAMA EĞİTİMİ</small></span></a><div class="portal-label"><span>3+1</span>{{ $portal }}</div><nav><a class="nav-item {{ $page==='dashboard'?'current':'' }}" href="/panel"><i class="bi bi-grid" aria-hidden="true"></i>Genel bakış</a><span class="nav-caption">ÇALIŞMA ALANIM</span>
@foreach($priority as $name)@if(isset($resources[$name]))<a class="nav-item {{ $page===$name?'current':'' }}" href="/panel/{{ $name }}"><i class="bi bi-{{ in_array($name,['students','companies'])?'people':(in_array($name,['placements','offers'])?'building':'journal-text') }}" aria-hidden="true"></i>{{ config('portal.labels.'.$name) }}</a>@endif @endforeach
@if(in_array($role,['mudur','mue_komisyon','bolum_komisyon','program_baskani']))<a class="nav-item {{ $page==='matching'?'current':'' }}" href="/panel/matching"><i class="bi bi-diagram-3" aria-hidden="true"></i>Akıllı eşleştirme</a>@endif
<a class="nav-item {{ $page==='ek'?'current':'' }}" href="/panel/ek"><i class="bi bi-ui-checks" aria-hidden="true"></i>EK form merkezi</a>
@if(in_array($role,['mudur','mue_komisyon','bolum_komisyon','program_baskani','koordinator','akademik_danisman']))<a class="nav-item" href="/panel/reports"><i class="bi bi-bar-chart" aria-hidden="true"></i>Rapor merkezi</a>@endif
@if(in_array($role,['bolum_komisyon','program_baskani']))<a class="nav-item" href="/panel/imports"><i class="bi bi-file-earmark-arrow-up" aria-hidden="true"></i>Öğrenci aktarımı</a>@endif
@if($role==='sistem_yoneticisi')<a class="nav-item" href="/panel/accounts"><i class="bi bi-person-gear" aria-hidden="true"></i>Hesap yönetimi</a>@endif
<span class="nav-caption">TÜM İŞLEMLER</span>@foreach(config('portal.groups') as $group=>$names)@php($available=array_filter($names,fn($n)=>isset($resources[$n])))@if($available)<details class="nav-group" @if(in_array($page,$available)&&!in_array($page,$priority)) open @endif><summary>{{ $group }}</summary>@foreach($available as $name)<a class="nav-item small {{ $page===$name?'current':'' }}" href="/panel/{{ $name }}">{{ config('portal.labels.'.$name) }}</a>@endforeach</details>@endif @endforeach
</nav><div class="sidebar-bottom"><i class="bi bi-shield-check" aria-hidden="true"></i><span>Görevinize özel erişim<br><small>Yetkiler sunucuda denetlenir.</small></span></div></aside>
<button type="button" id="menu-backdrop" class="menu-backdrop" aria-label="Menüyü kapat" hidden></button><div class="main-shell"><header class="topbar"><button class="btn menu-toggle" id="menu-toggle" aria-controls="sidebar" aria-expanded="false" aria-label="Menüyü aç"><i class="bi bi-list"></i></button><span class="topbar-unit">ELAZIĞ ORGANİZE SANAYİ BÖLGESİ MYO</span><div class="topbar-actions"><a href="/panel/notifications" class="icon-button" aria-label="Bildirimler"><i class="bi bi-bell"></i></a><div class="user-info"><span class="avatar">{{ mb_substr(auth()->user()->name,0,1) }}</span><span><b>{{ auth()->user()->name }}</b><small>{{ config('portal.values.'.$role) }}</small></span></div><a class="icon-button" href="/gorev" aria-label="Görev değiştir"><i class="bi bi-arrow-left-right"></i></a><form action="/cikis" method="post">@csrf<button class="icon-button" aria-label="Oturumu kapat"><i class="bi bi-box-arrow-right"></i></button></form></div></header>
<main id="main" class="page-content"><div class="breadcrumb-line"><a href="/panel">{{ $portal }}</a><span>/</span><span>{{ $title }}</span>@if($boot['record'])<span>/</span><span>Kayıt ayrıntısı</span>@endif</div><div class="page-heading"><div><span class="eyebrow">MESLEKİ UYGULAMA EĞİTİMİ</span><h1>{{ $title }}</h1><p id="page-description">{{ $page==='dashboard'?'Başvuru ve eğitim sürecinizdeki güncel durumu takip edin.':'Göreviniz kapsamında kayıtları inceleyin, işlemleri tamamlayın.' }}</p></div><span class="date-chip"><i class="bi bi-calendar3" aria-hidden="true"></i>{{ now()->timezone('Europe/Istanbul')->translatedFormat('d F Y') }}</span></div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($boot['demo'])<div class="alert alert-warning" role="status"><strong>DEMO ortamı.</strong> Öğrenci ve eğitim verileri sentetiktir; resmî karar veya belge taraması yapılmış sayılmaz. Belgesiz süreçler onaylanamaz.</div>@endif
<div id="page-error" role="alert" hidden></div><div id="workspace" aria-live="polite"><div class="loading-state"><span class="spinner-border spinner-border-sm" aria-hidden="true"></span> Kayıtlar yükleniyor…</div></div>
</main><footer class="page-footer"><span>Fırat Üniversitesi · 3+1 MUE</span><span>Görev ve kapsam esaslı erişim</span></footer></div></div>
<script id="portal-boot" type="application/json">{!! json_encode($boot,JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR) !!}</script>
@endsection
