from pathlib import Path
import json
root=Path('D:/MUE/backend')
resources={}
def add(name, fields, write, read=None, states=None, unique=None, ek=None):
    resources[name]={'fields':fields,'write':write.split(),'read':(read or 'mudur mue_komisyon bolum_komisyon program_baskani koordin ator'.replace('koordin ator','koordinator')).split(),'states':states or {},'unique':unique or [],'ek':ek}
def f(t, rule, ref=None): return {'type':t,'rules':rule,'ref':ref}
S=lambda r='required|string|max:250':f('string',r)
T=lambda r='required|string|max:20000':f('text',r)
J=lambda r='required|array':f('jsonb',r)
I=lambda r='required|integer|min:0':f('integer',r)
N=lambda r='required|numeric|min:0':f('decimal',r)
D=lambda r='required|date':f('date',r)
B=lambda r='required|boolean':f('boolean',r)
R=lambda table,req=True:f('uuid',('required' if req else 'nullable')+'|uuid',table)
admin='mudur program_baskani bolum_komisyon'
company='isletme_yetkilisi koordinator'
monitor='akademik_danisman egitici'
allread='mudur mue_komisyon bolum_komisyon program_baskani koordinator akademik_danisman egitici ogrenci isletme_yetkilisi belge_gorevlisi'
draft={'taslak':['gonderildi'],'gonderildi':['inceleniyor','iade'],'iade':['gonderildi'],'inceleniyor':['onaylandi','reddedildi','iade']}
add('institutions',{'code':S(),'name':S()},'sistem_yoneticisi',read=allread+' sistem_yoneticisi',unique=[['code']])
add('departments',{'code':S(),'name':S()},admin,read=allread,unique=[['institution_id','code']])
add('programs',{'department_id':R('departments'),'code':S(),'name':S(),'active_student_count':I(),'ects':N('required|numeric|in:30'),'workplace_hours':I('required|integer|in:600'),'independent_hours':I('required|integer|in:300'),'weeks':I('required|integer|in:15')},admin,read=allread,unique=[['institution_id','code']])
add('academic_terms',{'code':S(),'starts_on':D(),'ends_on':D('required|date|after:starts_on'),'application_deadline':f('timestamp','required|date'),'preference_opens_at':f('timestamp','required|date'),'preference_deadline':f('timestamp','required|date|after:preference_opens_at'),'placement_appeal_deadline':f('timestamp','nullable|date'),'academic_year_end':D(),'next_year_starts_on':D(),'pass_threshold':N('nullable|numeric|between:0,100'),'letter_grade_rules':J('nullable|array'),'holiday_dates':J(),'absence_warning_percent':N('nullable|numeric|between:0,20')},admin,read=allread,states={'taslak':['acik'],'acik':['eslestirme','kapali'],'eslestirme':['uygulama','kapali'],'uygulama':['degerlendirme'],'degerlendirme':['kapali']},unique=[['institution_id','code']])
add('companies',{'legal_name':S(),'organization_type':S('required|in:ozel,kamu,universite'),'tax_no':S('nullable|string|max:20'),'mersis_no':S('nullable|string|max:30'),'sgk_no':S('nullable|string|max:40'),'nace_code':S('nullable|string|max:20'),'sector':S(),'personnel_count':I(),'contact_name':S(),'contact_title':S(),'phone':S(),'email':S('required|email'),'kep':S('nullable|string|max:250'),'iban':S('nullable|string|regex:/^TR[0-9]{24}$/'),'address':T(),'ip_rights_agreement':T('nullable|string')},company,read=allread,states={'taslak':['inceleniyor'],'inceleniyor':['aktif','iade'],'iade':['inceleniyor'],'aktif':['askida','pasif'],'askida':['inceleniyor','pasif']},unique=[['institution_id','tax_no'],['institution_id','mersis_no']])
add('company_sites',{'name':S(),'province':S(),'district':S(),'address':T(),'shuttle':B('nullable|boolean'),'meal':B('nullable|boolean'),'capacity_type':S('required|in:ortak,ayri'),'total_capacity':I('nullable|integer|min:0'),'hazard_class':S('required|in:az_tehlikeli,tehlikeli,cok_tehlikeli')},company,read=allread)
add('students',{'user_id':f('bigint','required|integer','users'),'student_no':S(),'national_id':T('nullable|string|size:11'),'phone':S('nullable|string|max:30'),'address':T('nullable|string'),'iban':T('nullable|string|regex:/^TR[0-9]{24}$/'),'graduated_on':D('nullable|date'),'graduation_exception':B(),'academic_data':J(),'gpa':N('nullable|numeric|between:0,4'),'gpa_scale':N('required|numeric|in:4'),'academic_source':S(),'academic_fetched_at':f('timestamp','required|date')},'bolum_komisyon program_baskani',read=allread,unique=[['institution_id','student_no'],['user_id']])
add('role_assignments',{'user_id':f('bigint','required|integer','users'),'role':S('required|in:sistem_yoneticisi,mudur,mue_komisyon,bolum_komisyon,program_baskani,koordinator,akademik_danisman,isletme_yetkilisi,egitici,ogrenci,belge_gorevlisi'),'valid_from':f('timestamp','required|date'),'valid_until':f('timestamp','nullable|date|after:valid_from')},'sistem_yoneticisi mudur',read='sistem_yoneticisi mudur')
add('program_outputs',{'code':S(),'description':T(),'target_percent':N('required|numeric|between:0,100'),'board_document_id':R('documents')},admin,read=allread,unique=[['program_id','code']])
add('learning_outcomes',{'program_output_id':R('program_outputs'),'code':S(),'description':T(),'tyyc_component':S('required|in:bilgi,beceri,yetkinlik')},admin,read=allread,unique=[['program_id','code']])
add('term_programs',{'active_student_count':I(),'semester':I('required|integer|in:3,4'),'grouping_enabled':B(),'board_document_id':R('documents'),'cohort_rule':T(),'preference_opens_at':f('timestamp','required|date'),'preference_deadline':f('timestamp','required|date')},admin,read=allread,unique=[['term_id','program_id']])
add('trainer_qualifications',{'site_id':R('company_sites'),'user_id':f('bigint','required|integer','users'),'field':S(),'degree':S('required|in:lisans,onlisans,ustalik,teknik_ogretmenlik,mesleki_yeterlilik'),'experience_years':N('required|numeric|min:3'),'qualification_document_id':R('documents'),'pedagogy_document_id':R('documents',False),'ohs_document_id':R('documents'),'certificates':J(),'employment_started_on':D(),'duty_title':S(),'unit':S(),'backup_trainer':B(),'declaration_accepted':B('required|accepted')},company,read=allread,states=draft,ek=19)
add('company_assessments',{'site_id':R('company_sites'),'trainer_id':R('trainer_qualifications'),'program_suitable':B(),'technical_infrastructure':B(),'qualified_trainer':B(),'ohs_suitable':B(),'physical_conditions':B(),'activity_diversity':B(),'onsite_inspected':B(),'explanations':J(),'valid_from':D(),'valid_until':D('required|date|after:valid_from')},'bolum_komisyon koordinator',read=allread,states=draft,ek=5)
add('protocols',{'number':S(),'signed_on':D(),'valid_from':D(),'valid_until':D('required|date|after:valid_from'),'signed_document_id':R('documents'),'termination_notice_on':D('nullable|date'),'ip_rights_agreement':T(),'supersedes_id':R('protocols',False)},'mudur koordinator',read=allread,states={'taslak':['imza_bekliyor'],'imza_bekliyor':['aktif'],'aktif':['askida','feshedildi','suresi_doldu'],'askida':['aktif','feshedildi']})
add('protocol_scopes',{'protocol_id':R('protocols'),'site_id':R('company_sites')},'mudur koordinator',read=allread,unique=[['protocol_id','site_id','program_id']])
add('offers',{'site_id':R('company_sites'),'protocol_id':R('protocols'),'assessment_id':R('company_assessments'),'trainer_id':R('trainer_qualifications'),'capacity':I(),'interview_required':B(),'duties':T(),'transport_information':T()},company,read=allread,states={'taslak':['dogrulandi'],'dogrulandi':['onaylandi'],'onaylandi':['ilan_edildi'],'ilan_edildi':['kapali']},unique=[['term_id','site_id','program_id']])
add('capacity_requests',{'offer_id':R('offers'),'requested_capacity':I(),'reason':T()},company,read=allread,states=draft)
add('applications',{'district':S(),'transport_declaration':T(),'course_conditions':J(),'eligibility':S('nullable|in:uygun,eksik,uygun_degil'),'eligibility_reason':T('nullable|string'),'gpa_snapshot':N('nullable|numeric|between:0,4'),'gpa_source':S('nullable|string'),'gpa_recorded_at':f('timestamp','nullable|date')},'ogrenci',read=allread,states={'taslak':['gonderildi'],'gonderildi':['uygun','eksik','uygun_degil'],'eksik':['gonderildi']},unique=[['student_id','term_id']],ek=1)
add('preferences',{'application_id':R('applications'),'offer_id':R('offers'),'rank':I('required|integer|min:1'),'revision':I('required|integer|min:1'),'reachable':B(),'one_way_minutes':N('required|numeric|min:0'),'transport_verified':B(),'submitted_at':f('timestamp','nullable|date')},'ogrenci',read=allread,unique=[['application_id','revision','rank'],['application_id','revision','offer_id']])
add('interviews',{'application_id':R('applications'),'offer_id':R('offers'),'scheduled_at':f('timestamp','required|date'),'result':S('required|in:bekliyor,kabul,ret'),'reason_code':S('nullable|string'),'reason':T('nullable|string')},'isletme_yetkilisi',read=allread,states=draft,unique=[['application_id','offer_id']])
add('matching_policies',{'revision':I('required|integer|min:1'),'preference_weight':N('required|numeric|between:0,1'),'transport_weight':N('required|numeric|between:0,1'),'max_preferences':I('required|integer|between:1,100'),'transport_rules':J(),'seed':S(),'time_limit_seconds':I('required|integer|between:1,120'),'decision_document_id':R('documents')},'bolum_komisyon',states=draft,unique=[['term_id','program_id','revision']])
add('matching_runs',{'policy_id':R('matching_policies'),'snapshot':J(),'snapshot_hash':S(),'algorithm_version':S(),'solver_status':S('nullable|string'),'objective_values':J('nullable|array'),'result':J('nullable|array'),'failure_message':T('nullable|string')},'bolum_komisyon',states={})
add('candidate_scores',{'run_id':R('matching_runs'),'application_id':R('applications'),'offer_id':R('offers'),'eligible':B(),'reasons':J(),'rank':I('nullable|integer|min:1'),'preference_score':N('nullable|numeric|min:0'),'transport_score':N('nullable|numeric|min:0'),'score':N('nullable|numeric|min:0')},'bolum_komisyon')
add('match_results',{'run_id':R('matching_runs'),'application_id':R('applications'),'offer_id':R('offers',False),'explanation':J()},'bolum_komisyon',read=allread,unique=[['run_id','application_id']])
add('placements',{'application_id':R('applications'),'offer_id':R('offers'),'run_id':R('matching_runs',False),'starts_on':D(),'ends_on':D('required|date|after_or_equal:starts_on'),'previous_placement_id':R('placements',False),'credited_minutes':I(),'credited_outcomes':J(),'reason':T('nullable|string'),'online_decision_id':R('decisions',False)},'bolum_komisyon',read=allread,states={'onerildi':['bolum_incelemesi'],'bolum_incelemesi':['onaylandi'],'onaylandi':['ilan_edildi'],'ilan_edildi':['baslamaya_hazir'],'baslamaya_hazir':['basladi'],'basladi':['tamamlandi','askida'],'askida':['basladi','degistirildi']})
add('decisions',{'target_type':S(),'target_id':f('uuid','required|uuid'),'decision_no':S(),'decision_on':D(),'document_id':R('documents'),'stage':S('required|in:bolum,mue,mudurluk,kurul'),'outcome':S('required|in:onay,ret,iade,askiya_alma,fesih'),'reason':T(),'meeting_date':D(),'members_count':I('required|integer|min:1'),'attendees_count':I('required|integer|min:1'),'votes_for':I(),'votes_against':I(),'chair_vote_for':B()},'mue_komisyon mudur bolum_komisyon',unique=[['institution_id','decision_no','target_type','target_id']])
add('publications',{'revision':I('required|integer|min:1'),'decision_document_id':R('documents'),'published_at':f('timestamp','required|date')},'mudur',read=allread,unique=[['term_id','revision']])
add('publication_items',{'publication_id':R('publications'),'target_type':S('required|in:placements,success_results'),'target_id':f('uuid','required|uuid'),'target_version':I(),'content':J()},'mudur',read=allread,unique=[['publication_id','target_type','target_id']])
add('appeals',{'target_type':S('required|in:placements,success_results'),'target_id':f('uuid','required|uuid'),'reason':T(),'document_id':R('documents',False),'decision_id':R('decisions',False)},'ogrenci',read=allread,states={'alindi':['inceleniyor'],'inceleniyor':['kabul','ret'],'kabul':['uygulandi']})
add('change_requests',{'new_offer_id':R('offers'),'reason':T(),'interruption_on':D('nullable|date'),'student_fault':B(),'credited_minutes':I(),'credited_outcomes':J(),'directorate_document_id':R('documents',False)},'ogrenci isletme_yetkilisi akademik_danisman',read=allread,states={'talep':['inceleniyor'],'inceleniyor':['onaylandi','reddedildi'],'onaylandi':['uygulandi']})
add('adviser_assignments',{'user_id':f('bigint','required|integer','users'),'valid_from':D(),'valid_until':D('required|date|after_or_equal:valid_from')},admin,read=allread,unique=[['student_id','term_id','user_id']])
add('trainer_assignments',{'trainer_id':R('trainer_qualifications'),'valid_from':D(),'valid_until':D('required|date|after_or_equal:valid_from')},'isletme_yetkilisi bolum_komisyon',read=allread,unique=[['placement_id','trainer_id']])
add('learning_plans',{'revision':I('required|integer|min:1'),'total_hours':I('required|integer|in:900'),'workplace_hours':I('required|integer|in:600'),'report_portfolio_hours':I('required|integer|in:300'),'orientation_hours':N(),'student_signed_document_id':R('documents'),'trainer_signed_document_id':R('documents'),'adviser_signed_document_id':R('documents'),'revision_reason':T('nullable|string')},monitor,read=allread,states=draft,unique=[['placement_id','revision']],ek=16)
add('plan_outcomes',{'plan_id':R('learning_plans'),'outcome_id':R('learning_outcomes'),'activity':T(),'expected_hours':N(),'evidence_sources':J('required|array|min:2'),'rubric_code':S('required|in:R-1,R-2,R-3,R-4,R-5'),'planned_weeks':J('required|array|min:1')},monitor,read=allread,unique=[['plan_id','outcome_id']])
add('weekly_plan_tasks',{'plan_id':R('learning_plans'),'outcome_id':R('learning_outcomes'),'week_no':I('required|integer|between:1,15'),'activity':T(),'expected_evidence':T(),'expected_hours':N(),'completion':S('required|in:planlandi,tam,kismi'),'trainer_approved':B(),'risk_item_id':R('risk_items')},monitor,read=allread)
add('attendance',{'date':D(),'planned_minutes':I('required|integer|between:1,1440'),'attended_minutes':I('required|integer|min:0|lte:planned_minutes'),'mark':S('required|in:V,Y,I,R'),'absence_reason':T('nullable|string'),'shift_type':S('required|in:gunduz'),'trainer_approved':B(),'adviser_reviewed':B()},'egitici',read=allread,states=draft,unique=[['placement_id','date']],ek=2)
add('weekly_reports',{'week_no':I('required|integer|between:1,15'),'week_start':D(),'week_end':D('required|date|after_or_equal:week_start'),'unit':S(),'activity_text':T(),'knowledge_skills':T(),'problems_solutions':T(),'revision':I('required|integer|min:1'),'trainer_review':T('nullable|string'),'adviser_review':T('nullable|string')},'ogrenci',read=allread,states={'taslak':['gonderildi'],'gonderildi':['egitici_onayi','iade'],'egitici_onayi':['danisman_onayi','iade'],'iade':['gonderildi']},unique=[['placement_id','week_no','revision']],ek=9)
add('report_outcomes',{'report_id':R('weekly_reports'),'outcome_id':R('learning_outcomes'),'document_id':R('documents',False)},'ogrenci',read=allread,unique=[['report_id','outcome_id']])
add('portfolio_evidence',{'outcome_id':R('learning_outcomes'),'document_id':R('documents'),'evidence_type':S('required|in:rapor,gorsel,teknik,olcum,ekipman,isg,organizasyon,sunum,video,gunluk,sertifika,plan,oz_degerlendirme'),'protected_material':B(),'company_permission_id':R('documents',False),'self_assessment':I('required|integer|between:1,4'),'description':T(),'consent_reference':S()},'ogrenci',read=allread,states=draft,ek=17)
add('self_assessments',{'outcome_id':R('learning_outcomes'),'phase':S('required|in:donem_basi,donem_sonu'),'level':I('required|integer|between:1,4'),'evidence_id':R('portfolio_evidence',False),'transferable_competencies':J(),'reflection_answers':J('required|array|size:5'),'portfolio_checklist':J('required|array|size:13')},'ogrenci',read=allread,states=draft,ek=17)
add('inspections',{'inspected_at':f('timestamp','required|date'),'mode':S('required|in:yuz_yuze,cevrim_ici'),'workplace_inspection':B(),'unannounced':B(),'findings':T(),'actions':T(),'criteria_scores':J('required|array|size:6'),'document_id':R('documents'),'online_record_id':R('online_records',False)},'akademik_danisman',read=allread,states=draft,ek=4)
add('online_records',{'occurred_at':f('timestamp','required|date'),'platform':S(),'participants':J('required|array|min:1'),'summary':T(),'next_steps':T(),'decision_id':R('decisions'),'document_id':R('documents')},'akademik_danisman',read=allread,states=draft,ek=13)
add('rubric_versions',{'code':S(),'revision':I(),'criteria':J('required|array|min:1'),'levels':J('required|array|min:4'),'board_document_id':R('documents')},admin,read=allread,states=draft,unique=[['program_id','code','revision']])
add('rubric_evaluations',{'rubric_id':R('rubric_versions'),'outcome_id':R('learning_outcomes'),'source':S('required|in:is_yeri,danisman,dosya_portfolyo,sunum'),'area':S('required|in:mesleki,problem,takim,etik,isg,belgeleme'),'criterion_values':J('required|array|min:1'),'level':I('required|integer|between:1,4'),'behavior_evidence':T(),'score':N('required|numeric|between:0,100'),'evidence_document_id':R('documents'),'revision':I()},'egitici akademik_danisman',read=allread,states=draft,ek=3)
add('presentations',{'presented_on':D(),'criteria_scores':J('required|array|size:5'),'document_id':R('documents'),'commission_member_id':f('bigint','required|integer','users'),'comments':T()},'akademik_danisman bolum_komisyon',read=allread,states=draft,ek=11)
add('training_file_deliveries',{'paper_delivered_on':D(),'electronic_document_id':R('documents'),'electronic_delivered_on':D(),'trainer_approval_document_id':R('documents')},'ogrenci',read=allread,states=draft)
add('success_results',{'revision':I(),'component_scores':J(),'area_scores':J(),'absence_percent':N(),'total_score':N(),'outcome':S(),'letter_grade':S('nullable|string'),'reasons':J(),'evaluation_available':B(),'calculation_version':S()},'akademik_danisman bolum_komisyon',read=allread,states={'hesaplandi':['onaylandi'],'onaylandi':['ilan_edildi']},unique=[['student_id','term_id','revision']])
add('declarations',{'form_code':S('required|in:EK-8,EK-10'),'text_version':S(),'accepted':B('required|accepted'),'signed_document_id':R('documents'),'accepted_at':f('timestamp','required|date')},'ogrenci',read=allread,unique=[['placement_id','form_code']])
add('ohs_records',{'trained_on':D(),'hours':N('required|numeric|min:0.01'),'trainer_name':S(),'risks_explained':T(),'ppe_items':J('required|array|min:1'),'emergency_orientation':B('required|accepted'),'training_document_id':R('documents'),'ppe_delivery_document_id':R('documents')},'egitici isletme_yetkilisi',read=allread,states=draft)
add('insurance_records',{'starts_on':D(),'ends_on':D('required|date|after_or_equal:starts_on'),'entry_document_id':R('documents'),'submitted_to_company_on':D(),'general_health_required':B(),'premium_paid':B(),'documents_complete':B()},'belge_gorevlisi',read='mudur mue_komisyon bolum_komisyon belge_gorevlisi ogrenci',states=draft)
add('financial_policies',{'revision':I(),'valid_from':D(),'valid_until':D(),'net_minimum_wage':N(),'minimum_wage_rate':N('required|numeric|between:0,1'),'contribution_extension_confirmed':B(),'contribution_under20':N('required|numeric|between:0,1'),'contribution_20plus':N('required|numeric|between:0,1'),'legal_reference_document_id':R('documents')},'belge_gorevlisi',states=draft)
add('payroll',{'month':S('required|date_format:Y-m'),'personnel_count':I(),'worked_days':I('required|integer|between:0,31'),'net_paid':N(),'gross_paid':N(),'payment_on':D(),'student_iban':T('required|string|regex:/^TR[0-9]{24}$/'),'bank_account_student_owned':B('required|accepted'),'receipt_document_id':R('documents'),'payroll_document_id':R('documents'),'financial_policy_id':R('financial_policies'),'reported_on':D(),'minimum_due':N('nullable|numeric'),'state_contribution':N('nullable|numeric'),'employer_share':N('nullable|numeric')},'isletme_yetkilisi belge_gorevlisi',read='mudur mue_komisyon belge_gorevlisi ogrenci',states=draft,unique=[['placement_id','month']],ek=12)
add('fund_contributions',{'payroll_id':R('payroll'),'aphb_document_id':R('documents'),'student_certificate_id':R('documents'),'reported_on':D(),'claimed_months':I(),'declaration_accepted':B('required|accepted'),'bank_branch':S(),'attachments_checklist':J(),'total_claim':N('nullable|numeric')},'isletme_yetkilisi belge_gorevlisi',read='mudur mue_komisyon belge_gorevlisi ogrenci',states=draft,ek=15)
add('nonconformities',{'type':S('required|in:devamsizlik,disiplin,isg,amac_disi,diger'),'occurred_at':f('timestamp','required|date'),'description':T(),'proposed_action':T(),'decision_id':R('decisions',False),'directorate_document_id':R('documents',False),'authorized_failure':B()},monitor+' isletme_yetkilisi',read='mudur mue_komisyon bolum_komisyon akademik_danisman egitici ogrenci',states={'taslak':['gonderildi'],'gonderildi':['inceleniyor'],'inceleniyor':['karar_verildi'],'karar_verildi':['kapandi']},ek=6)
add('incidents',{'type':S('required|in:is_kazasi,ramak_kala,meslek_hastaligi'),'occurred_at':f('timestamp','required|date'),'location':S(),'witnesses':J(),'health_facility':S('nullable|string'),'description':T(),'first_response':T(),'sgk_notified_at':f('timestamp','nullable|date'),'directorate_notified_at':f('timestamp','nullable|date'),'official_notification_status':S('required|in:yapildi,yapilacak'),'investigation_document_id':R('documents',False)},monitor+' isletme_yetkilisi',read='mudur mue_komisyon akademik_danisman egitici ogrenci',states=draft,ek=7)
add('feedback',{'source_role':S('required|in:ogrenci,isletme_yetkilisi,egitici,akademik_danisman,mezun,isveren,danisma_kurulu'),'items':J('required|array|size:5'),'comments':T('nullable|string')},'ogrenci isletme_yetkilisi egitici akademik_danisman',read='mudur mue_komisyon bolum_komisyon koordinator',states=draft,ek=14)
add('company_performance',{'site_id':R('company_sites'),'academic_year':S(),'criterion_scores':J('required|array|size:8'),'evidence_documents':J('required|array|min:1'),'previous_score':N('nullable|numeric'),'total_score':N('nullable|numeric'),'authorization_years':I('nullable|integer'),'authorization_until':D('nullable|date'),'corrective_action':T('nullable|string')},'koordinator bolum_komisyon',states=draft,ek=18)
add('annual_reports',{'academic_year':S(),'statistics':J(),'outcome_attainment':J(),'stakeholder_feedback':J(),'inspection_summary':J(),'ohs_statistics':J(),'root_causes':J(),'previous_actions_effects':J(),'conclusion':T(),'board_document_id':R('documents',False)},'bolum_komisyon mue_komisyon',states=draft,ek=18)
add('improvement_actions',{'annual_report_id':R('annual_reports',False),'inspection_id':R('inspections',False),'program_output_id':R('program_outputs',False),'owner_user_id':f('bigint','required|integer','users'),'finding':T(),'action':T(),'root_cause':T(),'due_on':D(),'resource_need':T(),'indicator':T(),'effect_evidence':T('nullable|string'),'remeasured_value':N('nullable|numeric')},'bolum_komisyon mue_komisyon akademik_danisman koordinator',states={'acik':['uygulaniyor'],'uygulaniyor':['kontrol_edildi'],'kontrol_edildi':['kapandi','uygulaniyor']})
add('risk_plans',{'site_id':R('company_sites'),'assessed_on':D(),'renewal_on':D(),'team':J('required|array|min:5'),'general_assessment_current':B(),'hazard_checklist':J('required|array|size:16'),'emergency_scenarios':J('required|array|size:6'),'emergency_contacts':J('required|array|min:1'),'nearest_exit':S(),'assembly_area':S(),'first_aid_location':S(),'extinguisher_location':S(),'drill_on':D('nullable|date'),'orientation_on':D(),'signed_document_id':R('documents')},company,read=allread,states=draft,ek=20)
add('risk_items',{'risk_plan_id':R('risk_plans'),'activity':T(),'hazard':T(),'possible_result':T(),'controls':T(),'probability':I('required|integer|between:1,5'),'severity':I('required|integer|between:1,5'),'residual_probability':I('required|integer|between:1,5'),'residual_severity':I('required|integer|between:1,5'),'mitigation_completed':B(),'direct_supervision':B(),'responsible_user_id':f('bigint','required|integer','users'),'due_on':D()},company,read=allread)
add('recognition_requests',{'previous_institution':S(),'previous_hours':N(),'previous_ects':N(),'outcome_comparison':J(),'adaptation_opinion_document_id':R('documents'),'board_decision_id':R('decisions',False)},'ogrenci bolum_komisyon',read=allread,states=draft)
add('change_control',{'request_no':S(),'description':T(),'reason':T(),'affected_requirements':J(),'migration_impact':T(),'security_impact':T(),'test_impact':T(),'estimated_effort':T(),'target_version':S(),'decision_id':R('decisions',False)},admin+' sistem_yoneticisi',states=draft)
add('documents',{'target_type':S(),'target_id':f('uuid','required|uuid'),'object_key':S(),'original_name':S(),'mime':S(),'size_bytes':I(),'sha256':S(),'scan_status':S(),'classification':S('required|in:kurum_ici,gizli,saglik,disiplin'),'retention_start_event':S(),'retention_until':D(),'legal_hold':B(),'supersedes_id':R('documents',False)},allread,read=allread)
add('import_batches',{'source':S(),'sha256':S(),'rows':J(),'errors':J(),'accepted_count':I()},'bolum_komisyon program_baskani',unique=[['institution_id','sha256']])
add('notifications',{'recipient_id':f('bigint','required|integer','users'),'event_key':S(),'channel':S(),'message':T(),'read_at':f('timestamp','nullable|date'),'sent_at':f('timestamp','nullable|date'),'retry_count':I()},'sistem_yoneticisi',read=allread,unique=[['recipient_id','event_key','channel']])
add('outbox_events',{'event_type':S(),'aggregate_id':f('uuid','required|uuid'),'recipient_ids':J(),'payload':J(),'processed_at':f('timestamp','nullable|date')},'sistem_yoneticisi',read='sistem_yoneticisi')
# Parent FK context requirements are authoritative, not client-editable.
context_required={
 'departments':['institution_id'],'programs':['institution_id'],'academic_terms':['institution_id'],
 'companies':['institution_id'],'company_sites':['company_id'],'students':['program_id'],
 'program_outputs':['program_id'],'learning_outcomes':['program_id'], 'term_programs':['program_id','term_id'],
 'trainer_qualifications':['company_id'],'company_assessments':['company_id','program_id'],
 'protocols':['company_id'],'protocol_scopes':['program_id'], 'offers':['term_id','program_id','company_id'],
 'applications':['student_id','term_id'],'adviser_assignments':['student_id','term_id'],
 'matching_policies':['term_id','program_id'], 'publications':['term_id'],
}
placement_tables='trainer_assignments learning_plans weekly_plan_tasks attendance weekly_reports portfolio_evidence self_assessments inspections online_records rubric_evaluations presentations training_file_deliveries success_results declarations ohs_records insurance_records payroll fund_contributions nonconformities incidents change_requests'.split()
for k in placement_tables: context_required[k]=['placement_id']
for k,v in resources.items(): v['required_context']=context_required.get(k,['institution_id'])
def php(value):
 if isinstance(value,dict): return '['+',\n'.join(php(k)+'=>'+php(v) for k,v in value.items())+']'
 if isinstance(value,list): return '['+','.join(php(x) for x in value)+']'
 if value is None: return 'null'
 if isinstance(value,bool): return 'true' if value else 'false'
 if isinstance(value,(int,float)): return str(value)
 return "'"+value.replace('\\','\\\\').replace("'","\\'")+"'"
(root/'config/domain.php').write_text('<?php\nreturn '+php(resources)+';\n',encoding='utf8')
(root/'../docs/resource-manifest.json').write_text(json.dumps(resources,ensure_ascii=False,indent=2),encoding='utf8')
print('Typed resources:',len(resources))
