import 'bootstrap/dist/js/bootstrap.bundle.min.js';
import{B,pageError}from'./portal/core';
import{renderPage}from'./portal/views';
document.addEventListener('click',e=>{const button=e.target.closest('[data-close-dialog]');if(button)button.closest('dialog').close();const toggle=e.target.closest('[data-toggle-password]');if(toggle){const input=document.getElementById(toggle.dataset.togglePassword);input.type=input.type==='password'?'text':'password';toggle.setAttribute('aria-label',input.type==='password'?'Parolayı göster':'Parolayı gizle');}});
function setMenu(expanded){const sidebar=document.getElementById('sidebar');if(!sidebar)return;sidebar.classList.toggle('visible',expanded);document.getElementById('menu-toggle').setAttribute('aria-expanded',String(expanded));document.getElementById('menu-backdrop').hidden=!expanded;document.querySelector('.main-shell').inert=expanded&&window.innerWidth<=780;if(expanded)document.getElementById('menu-close').focus();else document.getElementById('menu-toggle').focus();}document.getElementById('menu-toggle')?.addEventListener('click',()=>setMenu(!document.getElementById('sidebar').classList.contains('visible')));for(const id of ['menu-close','menu-backdrop'])document.getElementById(id)?.addEventListener('click',()=>setMenu(false));document.addEventListener('keydown',e=>{if(e.key==='Escape'&&document.getElementById('sidebar')?.classList.contains('visible'))setMenu(false);});window.addEventListener('resize',()=>{if(window.innerWidth>780&&document.getElementById('sidebar')?.classList.contains('visible'))setMenu(false);});
if(B)renderPage().catch(pageError);

// Browser constraint bubbles also use the same Turkish labels.
document.addEventListener('invalid',e=>{const input=e.target;const label=input.labels?.[0]?.textContent?.trim().replace('*','').trim()||'Alan';input.setCustomValidity(label+' alanını geçerli bir değerle doldurun.');},true);document.addEventListener('input',e=>e.target.setCustomValidity?.(''));document.addEventListener('change',e=>e.target.setCustomValidity?.(''));
